---
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
spec:
  apiServer:
    caBundleFileMountPath: ""
    caBundleFileName: ""
    cacheEnabled: true
    deploy: true
    enableOauth: true
    enableSamplePipeline: false
    managedPipelines: {}
    pipelineStore: kubernetes
  database:
    disableHealthCheck: false
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
      pvcSize: 10Gi
      username: mlpipeline
  dspVersion: v2
  objectStorage:
    disableHealthCheck: false
    enableExternalRoute: false
    externalStorage:
      basePath: ""
      bucket: pipeline
      host: minio-pipeline:9000
      port: ""
      region: us
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: dashboard-dspa-secret
      scheme: http
  persistenceAgent:
    deploy: true
    numWorkers: 2
  podToPodTLS: true
  scheduledWorkflow:
    cronScheduleTimezone: UTC
    deploy: true
