---
apiVersion: v1
kind: Secret
metadata:
  name: aws-connection-minio-pipeline
  annotations:
    opendatahub.io/connection-type: s3
    opendatahub.io/connection-type-protocol: s3
    opendatahub.io/connection-type-ref: s3
    openshift.io/display-name: MinIO Pipeline
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123minio123
  AWS_S3_ENDPOINT: http://minio-pipeline:9000
  AWS_S3_BUCKET: pipeline
  AWS_DEFAULT_REGION: us
