---
apiVersion: v1
kind: Secret
metadata:
  name: llama-stack-connection
  annotations:
    openshift.io/display-name: LlamaStack AutoRAG
type: Opaque
stringData:
  LLAMA_STACK_CLIENT_BASE_URL: "http://lsd-genai-playground-service:8321"
  LLAMA_STACK_CLIENT_API_KEY: "unused"
  OGX_CLIENT_BASE_URL: "http://lsd-genai-playground-service:8321"
  OGX_CLIENT_API_KEY: "unused"
